# Generated by Django 4.0.4 on 2022-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nectaapi',
            name='maths',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
